-- Batch 2: Getting Started (5 more) + Tutorials (5 posts)

INSERT INTO blog_posts (title, slug, excerpt, content, featured_image, category, tags, status, reading_time, published_at, created_at) VALUES 
('Calibrating Sensors for Optimal Performance', 'calibrating-sensors', 'Complete calibration guide for accelerometer, gyroscope, and ESCs.', '<h2>When to Calibrate</h2><p>First setup, after firmware update, after crashes, when drone drifts, monthly maintenance.</p><h2>IMU Calibration</h2><p>Place on level surface, keep perfectly still for 30 seconds. Use app or Arduino code.</p><h2>ESC Calibration</h2><p>Remove propellers, follow app instructions for 15-second calibration sequence.</p><h2>Verification</h2><p>Check sensor readings, perform hover test to ensure minimal drift.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["calibration", "sensors", "IMU", "setup"]', 'published', 7, datetime('now', '-38 days'), datetime('now', '-38 days')),

('Troubleshooting Common Issues', 'troubleshooting-common-issues', 'Solutions to frequent problems: connection issues, motor problems, and flight instability.', '<h2>Connection Problems</h2><p>Can''t find Wi-Fi hotspot? Check LED indicators, verify drone is powered on, forget and reconnect network.</p><h2>Motor Issues</h2><p>Motors won''t spin? Check ESC connections, verify battery charge, recalibrate ESCs, inspect for physical damage.</p><h2>Flight Instability</h2><p>Drone drifts or flips? Recalibrate IMU, check propeller installation, verify motor directions, balance propellers.</p><h2>App Issues</h2><p>App crashes or disconnects? Update to latest version, clear cache, check device compatibility.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["troubleshooting", "problems", "support", "fixes"]', 'published', 6, datetime('now', '-36 days'), datetime('now', '-36 days')),

('Understanding Flight Modes Explained', 'understanding-flight-modes', 'Learn about different flight modes: Manual, Stabilize, Altitude Hold, and Position Hold.', '<h2>Manual Mode</h2><p>Full control with no stabilization. For experienced pilots only. Requires constant input for stable flight.</p><h2>Stabilize Mode</h2><p>Self-leveling when sticks centered. Best for beginners. Drone automatically returns to level flight.</p><h2>Altitude Hold</h2><p>Maintains current altitude automatically. Barometer keeps height constant. Easier hovering and photography.</p><h2>Position Hold (Vision only)</h2><p>GPS-based position lock. Drone stays in place without input. Ideal for hands-free hovering.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["flight modes", "stabilization", "beginners", "controls"]', 'published', 7, datetime('now', '-34 days'), datetime('now', '-34 days')),

('Reading and Understanding Telemetry Data', 'reading-telemetry-data', 'Understand telemetry displays: battery voltage, signal strength, altitude, and sensor readings.', '<h2>Battery Telemetry</h2><p>Voltage range 3.0V-4.2V. 3.7V = 50%. Below 3.5V = land soon. Real-time voltage and percentage display.</p><h2>Signal Strength</h2><p>RSSI shows Wi-Fi quality. -50dBm = excellent, -70dBm = good, -80dBm = poor.</p><h2>Flight Data</h2><p>Altitude, vertical speed, attitude angles, accelerations.</p><h2>Using Telemetry</h2><p>Monitor during flight, identify issues early, log data for analysis.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["telemetry", "data", "monitoring", "sensors"]', 'published', 6, datetime('now', '-32 days'), datetime('now', '-32 days')),

('Firmware Updates and Version Management', 'firmware-updates', 'How to update FLYQ firmware safely and manage different firmware versions.', '<h2>Why Update</h2><p>Bug fixes, new features, performance improvements, security patches.</p><h2>Update Process</h2><p>Connect via USB-C, open updater tool, download firmware, flash and verify.</p><h2>Backup First</h2><p>Save settings, export calibration data, backup custom code.</p><h2>Troubleshooting</h2><p>Try different USB cable, hold BOOT button, use recovery mode.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["firmware", "updates", "version", "maintenance"]', 'published', 7, datetime('now', '-30 days'), datetime('now', '-30 days')),

('Programming Custom LED Patterns', 'programming-led-patterns', 'Create stunning LED displays using Arduino code for FLYQ status lights.', '<h2>LED System</h2><p>PWR (GPIO12), SYS (GPIO13), LINK (GPIO14).</p><h2>Basic Control</h2><p>digitalWrite, PWM for fading, animations.</p><h2>Advanced Patterns</h2><p>Knight Rider, breathing, battery indicator.</p><h2>Wi-Fi Control</h2><p>Web server for remote LED control.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Tutorials', '["Arduino", "LED", "programming", "GPIO"]', 'published', 10, datetime('now', '-28 days'), datetime('now', '-28 days')),

('Building Your First Python Flight Script', 'first-python-flight-script', 'Write automated flight scripts with Python for takeoff, patterns, and landing.', '<h2>Basic Script</h2><p>Connect, takeoff, hover, land sequence.</p><h2>Square Pattern</h2><p>Program 2m x 2m flight path.</p><h2>Error Handling</h2><p>Try-except blocks, battery checks, emergency stop.</p><h2>Telemetry Logging</h2><p>CSV logging for analysis.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Tutorials', '["Python", "programming", "automation", "SDK"]', 'published', 12, datetime('now', '-26 days'), datetime('now', '-26 days')),

('Reading and Processing IMU Data', 'reading-imu-data', 'Access accelerometer and gyroscope data for custom flight algorithms.', '<h2>IMU Basics</h2><p>MPU6050 provides 3-axis data at 1000Hz.</p><h2>Reading Raw Data</h2><p>Wire.begin, getMotion6 functions.</p><h2>Data Filtering</h2><p>Complementary filter for attitude.</p><h2>Applications</h2><p>Stabilization, gestures, vibration monitoring.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Tutorials', '["IMU", "sensors", "data processing", "Arduino"]', 'published', 11, datetime('now', '-24 days'), datetime('now', '-24 days')),

('Creating a Web-Based Controller', 'web-based-controller', 'Build custom web interface for controlling FLYQ from any browser.', '<h2>Setup</h2><p>ESPAsyncWebServer library.</p><h2>HTML Interface</h2><p>Virtual joysticks, buttons, telemetry.</p><h2>WebSocket</h2><p>Real-time bidirectional control.</p><h2>Features</h2><p>Live video, gamepad support, mobile responsive.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Tutorials', '["web development", "controller", "Wi-Fi", "interface"]', 'published', 13, datetime('now', '-22 days'), datetime('now', '-22 days')),

('Implementing Altitude Hold with Barometer', 'altitude-hold-barometer', 'Use barometric pressure sensor for stable altitude hold functionality.', '<h2>BMP280</h2><p>Measures pressure for altitude ±1m accuracy.</p><h2>PID Controller</h2><p>Kp, Ki, Kd tuning for stability.</p><h2>Parameters</h2><p>Start Kp=2.0, Ki=0.5, Kd=1.0.</p><h2>Integration</h2><p>Combine with IMU, temperature compensation.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Tutorials', '["barometer", "altitude hold", "PID", "sensors"]', 'published', 10, datetime('now', '-20 days'), datetime('now', '-20 days'));
