-- Batch 1: Getting Started Posts (10 posts)

INSERT INTO blog_posts (title, slug, excerpt, content, featured_image, category, tags, status, reading_time, published_at, created_at) VALUES 
('Understanding Your FLYQ Drone Components', 'understanding-flyq-drone-components', 'Detailed guide to every component in your FLYQ drone kit and how they work together.', '<h2>The Flight Controller</h2><p>The ESP32-S3 dual-core processor runs at 240MHz handling all flight calculations. With 320KB SRAM and 4MB Flash, it manages sensor fusion, motor control, and wireless communication.</p><h2>Motor System</h2><p>Four 716 brushed motors provide thrust, each capable of 38,000 RPM. ESCs precisely control rotation speed for stable flight.</p><h2>Sensor Suite</h2><p>MPU6050 6-axis IMU provides accelerometer and gyroscope data essential for flight stabilization.</p><h2>Power System</h2><p>600mAh 3.7V LiPo battery delivers 8-10 minutes of flight time with built-in protection circuitry.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["components", "hardware", "ESP32-S3", "beginners"]', 'published', 6, datetime('now', '-50 days'), datetime('now', '-50 days')),

('FLYQ Safety Guidelines: Essential Rules', 'flyq-safety-guidelines', 'Comprehensive safety guidelines for safe drone operation indoors and outdoors.', '<h2>Pre-Flight Safety</h2><p>Always inspect propellers, motors, battery, and frame before flight. Check weather conditions and ensure adequate space.</p><h2>Flying Environment</h2><p>Indoor: minimum 3m x 3m x 2.5m. Outdoor: calm weather, away from people, within visual line of sight.</p><h2>Battery Safety</h2><p>Never leave charging unattended. Store at 50-60% charge. Dispose of damaged batteries properly.</p><h2>Emergency Procedures</h2><p>Know how to handle lost control, low battery warnings, and motor failures.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["safety", "guidelines", "best practices"]', 'published', 5, datetime('now', '-48 days'), datetime('now', '-48 days')),

('Setting Up Your Development Environment', 'setting-up-development-environment', 'Install Arduino IDE, Python, and FLYQ SDK for programming your drone.', '<h2>Arduino IDE Setup</h2><p>Download Arduino IDE 2.0+, install ESP32 board support, select ESP32-S3 Dev Module, and install required libraries: MPU6050, ESP32Servo, AsyncTCP.</p><h2>Python Environment</h2><p>Install Python 3.8+, create virtual environment, install FLYQ Python SDK and dependencies.</p><h2>Testing</h2><p>Upload blink test to Arduino, run Python connection test to verify setup.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["programming", "Arduino", "Python", "setup"]', 'published', 8, datetime('now', '-45 days'), datetime('now', '-45 days')),

('Your First Manual Flight: Basic Controls', 'first-manual-flight-controls', 'Master throttle, yaw, pitch, and roll for stable hovering and controlled flight.', '<h2>The Four Controls</h2><p>Throttle controls altitude, yaw rotates the drone, pitch moves forward/backward, roll moves left/right.</p><h2>First Flight Steps</h2><p>Takeoff to 1-1.5m, practice hovering for 30 seconds, make small corrections, land gently.</p><h2>Common Mistakes</h2><p>Avoid over-correcting, panic throttle cuts, flying too high initially, and ignoring battery level.</p><h2>Practice Progression</h2><p>Week 1: Hovering. Week 2: Basic movements. Week 3: Combined maneuvers and patterns.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["manual flight", "controls", "hovering", "flying skills"]', 'published', 9, datetime('now', '-42 days'), datetime('now', '-42 days')),

('Charging and Battery Care Guide', 'charging-battery-care', 'Essential guide to LiPo battery charging, maintenance, and safety practices.', '<h2>Charging Procedure</h2><p>Use only provided USB-C cable with 5V/2A adapter. Red LED = charging, Green LED = full. Takes 45-60 minutes from empty.</p><h2>Storage Best Practices</h2><p>Short-term: 50-80% charge. Long-term: 50-60% charge at room temperature.</p><h2>Warning Signs</h2><p>Replace battery if swollen, reduced flight time (<5 min), excessive heat, or physical damage.</p><h2>Battery Life</h2><p>Expected 300-500 charge cycles. Never discharge below 3.0V. Land at 20-30% remaining.</p>', 'https://cdn1.genspark.ai/user-upload-image/rmbg_generated/0_435c9a66-800a-4537-80f8-cd513ea4bf15', 'Getting Started', '["battery", "charging", "LiPo", "safety"]', 'published', 6, datetime('now', '-40 days'), datetime('now', '-40 days'));
